-- Add nutrition columns to food_logs table
ALTER TABLE public.food_logs
ADD COLUMN IF NOT EXISTS protein TEXT,
ADD COLUMN IF NOT EXISTS fat TEXT,
ADD COLUMN IF NOT EXISTS carbs TEXT,
ADD COLUMN IF NOT EXISTS sugar TEXT,
ADD COLUMN IF NOT EXISTS sodium TEXT,
ADD COLUMN IF NOT EXISTS calcium TEXT,
ADD COLUMN IF NOT EXISTS vitamin_c TEXT;